/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f3ebfa",
        "surface-container-highest": "#e8dfee",
        "surface-container-high": "#ede5f4",
        "surface-container-low": "#f9f1ff",
        "surface-container-lowest": "#ffffff",
        surface: "#fef7ff",
        "surface-bright": "#fef7ff",
        "surface-dim": "#dfd7e6",
        "surface-variant": "#e8dfee",
        "on-surface": "#1d1a24",
        "on-surface-variant": "#4a4455",
        "inverse-surface": "#332f39",
        "inverse-on-surface": "#f6eefc",
        background: "#fef7ff",
        "on-background": "#1d1a24",
        primary: "#630ed4",
        "on-primary": "#ffffff",
        "primary-container": "#7c3aed",
        "on-primary-container": "#ede0ff",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "primary-fixed-variant": "#7c3aed",
        "on-primary-fixed": "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "inverse-primary": "#d2bbff",
        "surface-tint": "#732ee4",
        secondary: "#4b41e1",
        "on-secondary": "#ffffff",
        "secondary-container": "#645efb",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#0f0069",
        "on-secondary-fixed-variant": "#3323cc",
        tertiary: "#7d3d00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a15100",
        "on-tertiary-container": "#ffe0cd",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#ffb784",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#713700",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        outline: "#7b7487",
        "outline-variant": "#ccc3d8",
        // legacy aliases kept for any old className references
        "text-primary": "#1D1A24",
        "text-secondary": "#4A4455",
        border: { DEFAULT: "#e5e7eb", soft: "#ccc3d8" },
        warning: "#F59E0B",
        success: "#16A34A",
        accent: { pink: "#EC4899", amber: "#F59E0B" },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        "container-max": "1280px",
        md: "24px",
        xs: "8px",
        gutter: "24px",
        sm: "16px",
        base: "4px",
        lg: "48px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "label-lg": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
